# Generated by Django 5.0.6 on 2024-07-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Reserved'), ('o', 'On loan'), ('a', 'Available'), ('m', 'Maintenance')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
